#coding:utf-8

"""
ID:          d06a25c844
ISSUE:       https://www.sqlite.org/src/tktview/d06a25c844
TITLE:       Incorrect result from a UNION with an ORDER BY
DESCRIPTION:
NOTES:
    [21.08.2025] pzotov
    Checked on 6.0.0.1232, 5.0.4.1701, 4.0.7.3231, 3.0.14.33824
"""

import pytest
from firebird.qa import *

db = db_factory()

test_script = """
    set list on;
    create table tx(id int generated by default as identity primary key, a int, b int);
    insert into tx(a,b) values(33,456);
    insert into tx(a,b) values(33,789);

    set count on;

    select distinct t0.id, t0.a, t0.b
    from tx as t0, tx as t1
    where t0.a=t1.a and t1.a=33 and t0.b=456
    UNION
    select distinct t0.id, t0.a, t0.b
    from tx as t0, tx as t1
    where t0.a=t1.a and t1.a=33 and t0.b=789
    order by 1;
"""

substitutions = [('[ \t]+', ' ')]
act = isql_act('db', test_script, substitutions = substitutions)

expected_stdout = """
    ID  1
    A  33
    B 456

    ID  2
    A  33
    B 789

    Records affected: 2
"""

@pytest.mark.version('>=3')
def test_1(act: Action):
    act.expected_stdout = expected_stdout
    act.execute(combine_output = True)
    assert act.clean_stdout == act.clean_expected_stdout
